---
title: Learn how to draw a flower
author: admin
date: '2020-02-17'
slug: RDrawFlower
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-02-17T20:41:23+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


## 学习绘制图形

> The scientist does not study nature because it is useful; he studies it because he delights in it, and he delights in it because it is beautiful.
> --*Henri Poincaré*

自然界中花的性状是可以被数学描述的，其中复杂性包括了很多如对称、分形等特殊形态。


```{r echo=FALSE, message=FALSE, warning=FALSE}
# Load the ggplot2 package
library(ggplot2)
```


首先从绘制一个圆圈开始。

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Create circle data to plot
t <- seq(0, 2*pi, length.out = 50)
x <- sin(t)
y <- cos(t)
df <- data.frame(t, x, y)

# Make a scatter plot of points in a circle
p <- ggplot(df, aes(x, y))
p + geom_point()
```

第二步在圆圈的基础上修改为螺旋，即满足斐波那契数列的原则，旋转角度为 $\pi*(3-\sqrt{5})$。

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Define the number of points
points <- 500


# Define the Golden Angle
angle <- pi * (3-sqrt(5))


t <- (1:points) * angle
x <- sin(t)
y <- cos(t)
df <- data.frame(t, x, y)

# Make a scatter plot of points in a spiral
p <- ggplot(df, aes(x*t, y*t))
p + geom_point()

```


第三步绘制花瓣颜色和调整大小。

```{r echo=FALSE, message=FALSE, warning=FALSE}
df <- data.frame(t, x, y)

# Make a scatter plot of points in a spiral and remove some plot components

p <- ggplot(df, aes(x*t, y*t))
p + geom_point(size=8, alpha=0.5, color="darkgreen") + theme_void()
```


第四步，将花瓣的大小设置为位置的函数，并调整花瓣形状。
```{r echo=FALSE, message=FALSE, warning=FALSE}
df <- data.frame(t, x, y)

# Make a scatter plot of points in a spiral and remove some plot components

p <- ggplot(df, aes(x*t, y*t))
p +  geom_point(size=t, alpha=0.5, shape=8)


```

第五步，将花瓣的大小设置为位置的函数，并调整花瓣形状，最后结果图。
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Change the values of angle and points
angle <- 13*pi/180
points <- 2000

t <- (1:points)*angle
x <- sin(t)
y <- cos(t)
df <- data.frame(t, x, y)

# Adjust the plot parameters to create the magenta flower
p <- ggplot(df, aes(x*t, y*t))
p + geom_point(size = 80, alpha = 0.1, shape = 1, color = 'magenta4')+
  theme(legend.position="none",
        panel.background = element_rect(fill = 'white'),
        panel.grid=element_blank(),
        axis.ticks=element_blank(),
        axis.title=element_blank(),
        axis.text=element_blank())
```
