---
title: 'Beta and Dirichlet regression'
subtitle: 'Beta and Dirichlet regression'
summary:
authors:
- admin
tags:
- Academic
categories:
- Demo
date: "2020-02-09T00:00:00Z"
lastmod: "2020-02-09T00:00:00Z"
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Placement options: 1 = Full column width, 2 = Out-set, 3 = Screen-width
# Focal point options: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
image:
  placement: 2
  caption: ''
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---


我们通常会使用线性回归，方差分析等方法来分析此类数据，回归统计在数据分析中非常重要，然而，对于一些比例数据，使用常见的线性回归则有不少弊端，例如，基于常见线性回归的预测结果可能会有负值，显然这是违反现实情况的。同时，此类方法的前提假设是因变量服从正态分布，然而正态分布本身包含从负无穷大到正无穷大的值，因此不太适合模拟比例数据。我们研究的对象数据只能在0到1之间取值。小于0或大于1的值没有意义。

对于计数的数据我们可以使用逻辑回归，但将计数的数据转化为连续的比例数据时（如动物行为时间比例），我们则需要选择β和Dirichlet分布对其进行分析。其中β回归用于分析只有一个因变量，而Dirichlet应用于多个因变量[Douma & Weedon, 2019](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13234)。

β回归针对的数据是分布于0到1之间的，以比例的形式出现。此外，也有将分布于a到b之间的数据转化为0到1的数据，转化公式为 $\frac{y-a}{b-a}$。同GLMs一样，β回归也包括3个部分，随机成分，系统成分和链接函数。β回归的假设条件为数据服从于β分布(Balakrishnan & Nevzorov, 2003)，β分布属于指数分布家族一员(Kieschnick & McCullough, 2003)，由2个参数控制。当数据中反应的类型超过2个类型时，β回归则扩展为Dirichlet 回归(Camargo, Stern, & Lauretto, 2012; Gueorguieva, Rosenheck, & Zelterman, 2008; Hijazi & Jernigan, 2009)。


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(DirichletReg)
library(readxl)
d <-read_excel("dataglmm.xlsx")

y <- DR_data(d[,c(3,4,6)])
x <- d[,c(9:14)]
plot(y, cex = 0.5, a2d = list(colored = FALSE, c.grid = FALSE))

summary(DirichReg(y ~ d$temp))

```


*此外，在`rmd`文件中设置`csv`文件路径，只能用相对路径，或者直接输入文件夹中的文件名即可，如`mazes <- read_csv("mazes.csv")`。*

